# =========================================
# Core Application Configuration
# =========================================
[core]
log_level = "INFO"
database_path = "data/" # Use a local 'data' directory for development

# =========================================
# Plugin-Specific Configurations
# =========================================
[plugins]

    [plugins.observability]
    enabled = true
    listen_address = "0.0.0.0:9600"

    [plugins.publish_service]
    enabled = true
    grpc_address = "0.0.0.0"
    grpc_port = 8090
    max_concurrent_streams = 250 

    [plugins.persistence_service]
    enabled = true

    # The file system path where the RocksDB database will be stored.
    # The application must have write permissions to this directory.
    storage_path = "data/persistence"

    # The number of recent blocks to keep in the 'hot' RocksDB tier.
    # Older blocks will be deleted (and archived to cold storage).
    hot_storage_block_count = 1000

    [plugins.subscribe_service]
    enabled = true
    grpc_port = 6890
    max_concurrent_streams = 250 

    [plugins.verification_service]
    enabled = false

    [plugins.block_access_service]
    enabled = true
    grpc_address = "0.0.0.0"
    grpc_port = 6791

    [plugins.server_status_service]
    enabled = true
    grpc_address = "0.0.0.0"
    grpc_port = 6792