# =========================================
# Core Application Configuration
# =========================================
[core]
log_level = "INFO"
database_path = "data/database"
start_block_number = 0

# =========================================
# Plugin-Specific Configurations
# =========================================
[plugins]

    [plugins.observability]
    enabled = true
    listen_address = "0.0.0.0:9600"

    [plugins.publish_service]
    enabled = true
    grpc_address = "0.0.0.0"
    grpc_port = 8090
    max_concurrent_streams = 250
    persistence_ack_timeout_seconds = 60
    stale_winner_timeout_seconds = 10
    winner_cleanup_interval_seconds = 150
    winner_cleanup_threshold_blocks = 1000

    [plugins.persistence_service]
    enabled = true
    cold_storage_path = "data/cold_storage"
    hot_storage_block_count = 100
    archive_batch_size = 100

    [plugins.state_management_service]
    enabled = true

    [plugins.ingress_service]
    enabled = true
    grpc_address = "0.0.0.0"
    grpc_port = 6896
    max_concurrent_streams = 100
    persistence_ack_timeout_seconds = 60
    stale_winner_timeout_seconds = 10
    winner_cleanup_interval_seconds = 150
    winner_cleanup_threshold_blocks = 1000
    backfill = { enabled = false, peers = [] }

    [plugins.subscriber_service]
    enabled = true
    grpc_port = 6895
    grpc_address = "0.0.0.0"
    max_concurrent_streams = 100
    live_stream_queue_size = 250
    max_future_block_lookahead = 250
    session_timeout_seconds = 60

    [plugins.verification_service]
    enabled = false

    [plugins.block_access_service]
    enabled = true
    grpc_address = "0.0.0.0"
    grpc_port = 6791

    [plugins.server_status_service]
    enabled = true
    grpc_address = "0.0.0.0"
    grpc_port = 6792

    [plugins.query_service]
    enabled = true
    grpc_address = "0.0.0.0"
    grpc_port = 6793
    