# =========================================
# Core Application Configuration
# =========================================
[core]
log_level = "INFO"
database_path = "data/database"
start_block_number = 0
grpc_address = "127.0.0.1"
grpc_port = 8090

# =========================================
# Plugin-Specific Configurations
# =========================================
[plugins]

    [plugins.observability]
    enabled = true
    listen_address = "127.0.0.1:9600"

    [plugins.publish_service]
    enabled = true
    max_concurrent_streams = 250
    persistence_ack_timeout_seconds = 60
    stale_winner_timeout_seconds = 10
    winner_cleanup_interval_seconds = 150
    winner_cleanup_threshold_blocks = 1000

    [plugins.persistence_service]
    enabled = true
    cold_storage_path = "data/cold_storage"
    hot_storage_block_count = 100
    archive_batch_size = 100

    [plugins.state_management_service]
    enabled = true

    [plugins.subscriber_service]
    enabled = true
    max_concurrent_streams = 100
    live_stream_queue_size = 250
    max_future_block_lookahead = 250
    session_timeout_seconds = 60

    [plugins.verification_service]
    enabled = false

    [plugins.block_access_service]
    enabled = true

    [plugins.server_status_service]
    enabled = true

    [plugins.query_service]
    enabled = true
    
    [plugins.backfill]
    enabled = true
    mode = "GapFill"
    peers = ["http://127.0.0.1:8090"]
    check_interval_seconds = 5
    max_batch_size = 10
