# =========================================
# Core Application Configuration
# =========================================
[core]
log_level = "INFO"
database_path = "data/database"

# =========================================
# Plugin-Specific Configurations
# =========================================
[plugins]

    [plugins.observability]
    enabled = true
    listen_address = "0.0.0.0:9600"

    [plugins.publish_service]
    enabled = true
    grpc_address = "0.0.0.0"
    grpc_port = 8090
    max_concurrent_streams = 250 

    [plugins.persistence_service]
    enabled = true

    # The sub-directory for cold storage archive files.
    cold_storage_path = "data/cold_storage"

    # The number of recent blocks to keep in the 'hot' RocksDB tier.
    hot_storage_block_count = 100

    # The number of blocks to bundle into a single cold storage archive file.
    archive_batch_size = 100

    # Add a placeholder for the future state service
    [plugins.state_service]
    enabled = false

    [plugins.subscriber_service]
    enabled = true
    grpc_port = 6895
    grpc_address = "0.0.0.0"
    max_concurrent_streams = 100
    live_stream_queue_size = 250
    max_future_block_lookahead = 250

    [plugins.verification_service]
    enabled = false

    [plugins.block_access_service]
    enabled = true
    grpc_address = "0.0.0.0"
    grpc_port = 6791

    [plugins.server_status_service]
    enabled = true
    grpc_address = "0.0.0.0"
    grpc_port = 6792