name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies (protoc)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y protobuf-compiler

      - name: Set up Rust toolchain (stable)
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          components: "rustfmt"

      - name: Cache cargo registry and build artifacts
        uses: Swatinem/rust-cache@v2

      - name: Build workspace (all crates & targets)
        run: cargo build --workspace --locked

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Install grcov
        run: cargo install grcov

      - name: Run unit tests with coverage
        env:
          CARGO_INCREMENTAL: "0"
          RUSTFLAGS: "-Cinstrument-coverage"
          LLVM_PROFILE_FILE: "target/coverage/default_%p_%m.profraw"
        run: cargo test --workspace --locked --exclude e2e

      - name: Generate lcov report
        run: |
          grcov . \
            --binary-path ./target/debug/deps/ \
            -s . \
            -t lcov \
            --branch \
            --ignore-not-existing \
            -o ./lcov.info \
            --ignore "tests/*" \
            --ignore "/*"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./lcov.info
          fail_ci_if_error: true
          verbose: true

